// <auto-generated />
using System;
using BracketSmasherBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BracketSmasherBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720062541_AddUniqueIndexToSetId")]
    partial class AddUniqueIndexToSetId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BracketSmasherBackend.Models.MatchSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CoinWinnerPlayerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CurrentTurnPlayerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Player1Connected")
                        .HasColumnType("boolean");

                    b.Property<long>("Player1Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("Player2Connected")
                        .HasColumnType("boolean");

                    b.Property<long>("Player2Id")
                        .HasColumnType("bigint");

                    b.Property<long>("SetId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SetId")
                        .IsUnique();

                    b.ToTable("MatchSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
