// <auto-generated />
using System;
using BracketSmasherBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BracketSmasherBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BracketSmasherBackend.Models.MatchResultReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LoserPlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("LoserScore")
                        .HasColumnType("integer");

                    b.Property<string>("LoserTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MatchSessionId")
                        .HasColumnType("uuid");

                    b.Property<long>("ReporterPlayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("SetId")
                        .HasColumnType("bigint");

                    b.Property<long>("WinnerPlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("WinnerScore")
                        .HasColumnType("integer");

                    b.Property<string>("WinnerTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MatchSessionId");

                    b.HasIndex("SetId", "ReporterPlayerId")
                        .IsUnique();

                    b.ToTable("MatchResultReports");
                });

            modelBuilder.Entity("BracketSmasherBackend.Models.MatchSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CoinWinnerPlayerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CurrentTurnPlayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Player1Connected")
                        .HasColumnType("boolean");

                    b.Property<long>("Player1Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("Player2Connected")
                        .HasColumnType("boolean");

                    b.Property<long>("Player2Id")
                        .HasColumnType("bigint");

                    b.Property<long>("SetId")
                        .HasColumnType("bigint");

                    b.Property<long>("TournamentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SetId")
                        .IsUnique();

                    b.ToTable("MatchSessions");
                });

            modelBuilder.Entity("BracketSmasherBackend.Models.StageBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BanOrder")
                        .HasColumnType("integer");

                    b.Property<long>("BannedByPlayerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatchSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchSessionId");

                    b.ToTable("StageBans");
                });

            modelBuilder.Entity("BracketSmasherBackend.Models.StageState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MatchSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UpdatedByPlayerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MatchSessionId");

                    b.ToTable("StageStates");
                });

            modelBuilder.Entity("BracketSmasherBackend.Models.MatchResultReport", b =>
                {
                    b.HasOne("BracketSmasherBackend.Models.MatchSession", "MatchSession")
                        .WithMany("ResultReports")
                        .HasForeignKey("MatchSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchSession");
                });

            modelBuilder.Entity("BracketSmasherBackend.Models.StageBan", b =>
                {
                    b.HasOne("BracketSmasherBackend.Models.MatchSession", "MatchSession")
                        .WithMany("StageBans")
                        .HasForeignKey("MatchSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchSession");
                });

            modelBuilder.Entity("BracketSmasherBackend.Models.StageState", b =>
                {
                    b.HasOne("BracketSmasherBackend.Models.MatchSession", "MatchSession")
                        .WithMany()
                        .HasForeignKey("MatchSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchSession");
                });

            modelBuilder.Entity("BracketSmasherBackend.Models.MatchSession", b =>
                {
                    b.Navigation("ResultReports");

                    b.Navigation("StageBans");
                });
#pragma warning restore 612, 618
        }
    }
}
